name: Update README File Structure

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Generate file structure
        run: |
            tree -aI '.git' 
            tree -aI '.git' > file_structure.txt

      - name: Update README.md
        run: |
            ls
            sed -i.bak '/## File Structure/,$d' README.md && rm README.md.bak
            echo '## File Structure' >> README.md
            echo '```' >> README.md
            cat file_structure.txt >> README.md
            echo '```' >> README.md

      - name: Commit changes
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m 'Update README file structure'
            git push
